const ReportUseCase = require('../../application/use-cases/ReportUseCase');
const logger = require('../../infrastructure/logging/logger');

exports.getOverdueBooks = async (req, res) => {
  try {
    const report = await ReportUseCase.getOverdueBooks();
    logger.info(`Overdue books report generated by ${req.user.id}`);
    res.json(report);
  } catch (error) {
    logger.error(`Error generating overdue report: ${error.message}`);
    res.status(500).json({ message: error.message });
  }
};

exports.getPopularBooks = async (req, res) => {
  try {
    const report = await ReportUseCase.getPopularBooks();
    logger.info(`Popular books report generated by ${req.user.id}`);
    res.json(report);
  } catch (error) {
    logger.error(`Error generating popular books report: ${error.message}`);
    res.status(500).json({ message: error.message });
  }
};

exports.getUserHistory = async (req, res) => {
  try {
    const userId = req.params.userId;
    const report = await ReportUseCase.getUserHistory(userId);
    logger.info(`User history report for user ${userId} generated by ${req.user.id}`);
    res.json(report);
  } catch (error) {
    logger.error(`Error generating user history report: ${error.message}`);
    res.status(500).json({ message: error.message });
  }
};

exports.getInventorySummary = async (req, res) => {
  try {
    const report = await ReportUseCase.getInventorySummary();
    logger.info(`Inventory summary report generated by ${req.user.id}`);
    res.json(report);
  } catch (error) {
    logger.error(`Error generating inventory summary report: ${error.message}`);
    res.status(500).json({ message: error.message });
  }
};
